### ISSUE TITLE
ManagedCode.Storage.Aws: BlobMetadata.Name has the same value as BlobMetadata.FullName

### ISSUE THREAD

**Issue by hoylu-royberg** [managedcode/Storage#92]
The `BlobMetadata.Name` property value contains both folder- and blob-name, so it's the same as `BlobMetadata.FullName`. I don't think that was the intention, as this is not the case with e.g. `ManagedCode.Storage.Azure`.

**Comment by KSemenenko** [comment]
please check 2.1.16

**Comment by hoylu-royberg** [comment]
Thank you for the fix 😊 However, it seems that now directory deletes are broken for AWS. I traced it down to this in `AWSStorage.DeleteDirectoryInternalAsync`:

```csharp
            await foreach (var item in items.WithCancellation(cancellationToken))
            {
                await StorageClient.DeleteAsync(StorageOptions.Bucket, item.FullName, null, cancellationToken);
            }
```

`item.FullName` needs to be changed to `item.Name`, because we send in bucket as the first parameter for the `DeleteAsync` call.
