### ISSUE TITLE
Regression: AWS directory deletes not working in 2.1.16

### ISSUE THREAD

**Issue by hoylu-royberg** [managedcode/Storage#94]
As mentioned in [issue 92](https://github.com/managedcode/Storage/issues/92#issuecomment-2151119383) directory deletes are broken for AWS. I traced it down to this:
https://github.com/managedcode/Storage/blob/eb9a11335786ac030b468fbf4426f0252821e82c/ManagedCode.Storage.Aws/AWSStorage.cs#L124

`item.FullName` needs to be changed to `item.Name`, because we send in bucket as the first parameter for the `DeleteAsync` call. Otherwise nothing is deleted. It's working fine for Azure. I have not tested GCP.

**Comment by KSemenenko** [comment]
check latest version

**Comment by KSemenenko** [comment]
@hoylu-royberg  fixed, try latest version

**Comment by hoylu-royberg** [comment]
Awesome -- thank you!

**Comment by hoylu-royberg** [comment]
Hmm, I don't see the updated version (yet): https://www.nuget.org/packages/ManagedCode.Storage.Aws#versions-body-tab
Still says .NET 8.0, and no new version today.

**Comment by hoylu-royberg** [comment]
Ah, I see it's being indexed now.
