### ISSUE TITLE
Feature request: Add support for AWS S3 IAM role based authentication

### ISSUE THREAD

**Issue by hoylu-royberg** [managedcode/Storage#96]
Similar to [issue 66 (using managed identities for Azure)](https://github.com/managedcode/Storage/issues/66), I would love to see support for [IAM role based authentication for AWS](https://docs.aws.amazon.com/AmazonS3/latest/userguide/security-iam.html), since using long term credentials are not an option in certain environments.

**Comment by hoylu-royberg** [comment]
I think all that is needed is to add a new constructor in [AWSStorage,cs](https://github.com/managedcode/Storage/blob/main/ManagedCode.Storage.Aws/AWSStorage.cs), that takes `InstanceProfileAWSCredentials` as input parameter.

**Comment by KSemenenko** [comment]
https://github.com/managedcode/Storage/releases/tag/2.1.20
